spring:
  application:
    name: Forge_Miniature_API

  datasource:
    url: jdbc:mysql://${DB_ENV_TEST}:${DB_PORT_TEST}/${DB_NAME_TEST}
    username: ${DB_USER_TEST}
    password: ${DB_PASS_TEST}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  management:
    endpoints:
      web:
        exposure:
          include: health,info,prometheus

jwt:
  secret: ${SECRET_TEST}
  expiration: ${JWT_EXPIRATION:3600000}
